import {
  Alert,
  Badge,
  Button,
  Breadcrumb,
  Cascader,
  Checkbox,
  Col,
  DatePicker,
  Dropdown,
  Form,
  Icon,
  Input,
  InputNumber,
  Layout,
  LocaleProvider,
  Menu,
  Modal,
  Pagination,
  Radio,
  Row,
  Spin,
  Select,
  Switch,
  Steps,
  Table,
  Tabs,
  Tag,
  TimePicker,
  Tooltip,
  Upload,
  Card,
  Timeline,
  Popover,
} from "ant-design-vue";

export default Vue => {
  Vue.use(Alert);
  Vue.use(Badge);
  Vue.use(Button);
  Vue.use(Breadcrumb);
  Vue.use(Breadcrumb.Item);
  Vue.use(Cascader);
  Vue.use(Checkbox);
  Vue.use(Checkbox.Group);
  Vue.use(Col);
  Vue.use(DatePicker);
  Vue.use(Dropdown);
  Vue.use(Form);
  Vue.use(Form.Item);
  Vue.use(Icon);
  Vue.use(Input);
  Vue.use(Input.TextArea);
  Vue.use(Input.Group);
  Vue.use(Input.Search);
  Vue.use(InputNumber);
  Vue.use(Layout);
  Vue.use(Layout.Content);
  Vue.use(Layout.Footer);
  Vue.use(Layout.Header);
  Vue.use(Layout.Sider);
  Vue.use(LocaleProvider);
  Vue.use(Menu);
  Vue.use(Menu.Item);
  Vue.use(Menu.ItemGroup);
  Vue.use(Menu.SubMenu);
  Vue.use(Modal);
  Vue.use(Pagination);
  Vue.use(Radio);
  Vue.use(Radio.Group);
  Vue.use(Radio.Button);
  Vue.use(Row);
  Vue.use(Spin);
  Vue.use(Select);
  Vue.use(Select.Option);
  Vue.use(Switch);
  Vue.use(Steps);
  Vue.use(Steps.Step);
  Vue.use(Table);
  Vue.use(Tabs);
  Vue.use(Tabs.TabPane);
  Vue.use(Tag);
  Vue.use(TimePicker);
  Vue.use(Tooltip);
  Vue.use(Upload);
  Vue.use(Dropdown);
  Vue.use(Card);
  Vue.use(DatePicker.MonthPicker);
  Vue.use(Timeline);
  Vue.use(Popover);

  Vue.prototype.$modal = Modal;
};
